# Build settings for the entire project.
[build]
  command = "npm run build"
  functions = "backend/functions"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "18"

# This is the NEW, specific rule for our API functions.
# It tells Netlify to rewrite requests from /api/* to the functions directory.
# This rule MUST come BEFORE the general /* rule.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# This is the general "catch-all" rule for our React frontend.
# It makes sure refreshing pages works correctly.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200