# This is the corrected configuration for a monorepo deployment on Netlify.

# Build settings for the entire project.
[build]
  command = "npm run build"
  functions = "backend/functions"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "18"

# API redirect rule
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback rule
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ---- NEW SECTION ----
# Per-function configuration.
# This block specifically targets the 'ingest-video' function.
[functions."ingest-video"]
  # Override the default 10-second timeout for this function only.
  timeout = 25